export const colorCombinationsData = [
  {
    id: "professional",
    name: "Professional Blue",
    description: "Trustworthy and reliable",
    primaryColor: "#1a365d",
    secondaryColor: "#3182ce",
    preview: "linear-gradient(to right, #1a365d, #3182ce)",
  },
  {
    id: "creative",
    name: "Creative Purple",
    description: "Imaginative and innovative",
    primaryColor: "#553c9a",
    secondaryColor: "#d53f8c",
    preview: "linear-gradient(to right, #553c9a, #d53f8c)",
  },
  {
    id: "minimal",
    name: "Minimal Black",
    description: "Elegant and sophisticated",
    primaryColor: "#1a202c",
    secondaryColor: "#4299e1",
    preview: "linear-gradient(to right, #1a202c, #4299e1)",
  },
  {
    id: "warm",
    name: "Warm Orange",
    description: "Friendly and approachable",
    primaryColor: "#744210",
    secondaryColor: "#ed8936",
    preview: "linear-gradient(to right, #744210, #ed8936)",
  },
  {
    id: "nature",
    name: "Nature Green",
    description: "Growth and harmony",
    primaryColor: "#22543d",
    secondaryColor: "#48bb78",
    preview: "linear-gradient(to right, #22543d, #48bb78)",
  },
  {
    id: "bold",
    name: "Bold Red",
    description: "Passionate and energetic",
    primaryColor: "#742a2a",
    secondaryColor: "#f56565",
    preview: "linear-gradient(to right, #742a2a, #f56565)",
  },
];